### ISSUE TITLE
IRepository<T>.Save

### ISSUE THREAD

**Issue by skorunka** [riteshrao/ncommon#12]
Im confused with IRepository<T>.Save method.
Especially in EF implementation, this method is used to Add/Insert object to repository not to Update/Save changes made on it.

How did you mean it?

**Comment by riteshrao** [comment]
Correct, it's meant to save transient instances. Updating entities is taken care of automatically via object tracking services for EF.

**Comment by skorunka** [comment]
So, may be we shoud rename it to "Add", "Save" is really confusing :)

**Comment by dplaskon** [comment]
Agreed; Add and Remove are better names for the repo methods.

**Comment by riteshrao** [comment]
Added Add in 1.1 branch and marked Save as obsolete.
