### ISSUE TITLE
Missing POCO support

### ISSUE THREAD

**Issue by marvealmar** [riteshrao/ncommon#14]
Trying to create a repository using POCO template in Visul Studio. Not able to save when using EFRepository cause its attach casts the TEntity to an IEntityWithKey (which the poco class) do not support. 

Poco support would be great:)

**Comment by coryt** [comment]
Any word on this?, We are considering ncommon but we are using EF with POCO's.

**Comment by marvealmar** [comment]
No.Have not heard anythin:)
I am trying out using Self Tracking entites on a project now. Guess I might have to write some UnitOfWorkFactory methods, and maybe a new Session class? I dont know much about this yet, havenot had the time to dive deep into it.

I guess it want be much problem using EF with pocos as you can attach it to the an objectcontext. I have the problem of needing to fill the repository with huge amount of data, this did result in that the objectcontext ran away with all my memory and I was not able to commit the UnitOfWork:(  So I cant use an objectcontext.

Apart from this I am very positive to NCommon and dont see no reason not to use it.

**Comment by riteshrao** [comment]
Full support for POCO and Code-Only has been in NCommon 1.1 branch for a while now.
