### ISSUE TITLE
Composite unit of work?

### ISSUE THREAD

**Issue by dplaskon** [riteshrao/ncommon#21]
I'm currently using Raven side-by-side with Nhibernate in a project. I'd ideally like to create a unit of work implementation for Raven itself (a trivial task). However, I'd love to have these two units of work use the same transaction, etc....have you considered some sort of composite unit of work implementation that would allow for several units of work to be used in conjunction?

**Comment by riteshrao** [comment]
Its something I'm definitely considering, and will be on the road map in one form or another for 2.0.

**Comment by dplaskon** [comment]
Great - thanks for the response!
