### ISSUE TITLE
Documentation and/or Examples

### ISSUE THREAD

**Issue by ghost** [riteshrao/ncommon#28]
NCommon looks like an awesome library, but is prohibitively difficult to navigate for a beginner of the patterns it covers. Could we have some documentation, please? the github pages have a well structured index, and would be really useful if the content is filled in.

Thanks in advance!

PS: I did take a look at the tests and the author's blog.

**Comment by riteshrao** [comment]
Working on it :)... been a bit strapped for time recently...

**Comment by marvealmar** [comment]
Hi,
I like the concept behind NCommon. But still I'm having problem finding any good documentation. The links at this page: http://riteshrao.github.com/ncommon/docs/, does not work. I want to use/try this framework but would very much be able to be able to support "my programming desicions" on a good, detailed and updated documentation. I also miss docs on the business and validation rule patterns/implementation.
So, can we expect to see updated documentation at the mentioned web site in the near future?
