### ISSUE TITLE
TransactionManager IDispose pattern.

### ISSUE THREAD

**Issue by skorunka** [riteshrao/ncommon#3]
Private field "_disposed" in "TransactionManager " class has never assigned value to.

Shouldn't it be set to true in "void Dispose(bool disposing)" function?

```
    void Dispose(bool disposing)
    {
        if ( !_disposed ) {
            if ( disposing ) {
                ...
            }
        }
        _disposed = true;
    }
```

**Comment by riteshrao** [comment]
Fixed in commit f19164a644ba5c1d57571fa9e327de4923248760
